coded brake and added solinoid stuff
FairportRobotics/AngelFish pull request #12
Opened 2023-03-10 01:37 UTC by RealGrimmCreeper

2023-03-10 13:45 UTC, jagiorgi requested changes
There are still come conflicts in some of the files and it does not build due to incorrect merging.

2023-03-10 19:04 UTC, tywilly requested changes

2023-03-10 19:04 UTC, tywilly commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> +    double wristPower = wristPIDController.calculate(wristAnalogInput.getValue()+armAnalogInput.getValue()-wristOffset);
Check the input for this PID controller. I don't think you want the arm position in the calculation for the wrist.

2023-03-11 14:00 UTC, tywilly approved these changes

2023-03-11 14:00 UTC, merged